### PR TITLE
Update Religions

### PR DESCRIPTION
**Pull request by gumboLewt**
Update religions in Outland
Replace tech_group limitations with religious ones

### CODE REVIEW

**Comment by Xanaa** [comment]
I hope that You know what are you doing...

**Comment by gumboLewt** [comment]
Updating to 1.18 wasn't done; seeing CTDs at game's beginning due to an AI issue. My current working theory is that it's an issue with the map but I'm not sure. Religious rebel changes also need more testing. Sorry, forgot this was still open.

**Comment by vawser** [comment]
Flag issue is related to Paradox reserving the EXX tags for dynamic use. I had the same issue in my ASOIAF mod. I'll try and get a compatability update out for 1.19 since I wouldn't want to see all your hard work wasted.

**Comment by gumboLewt** [comment]
Great, thank you!

**Pull request merged**
